# See LICENSE.vyoma for more details

# $1 = Test Name
# $2 = Test Directory
TEST_HOME=$PWD
OUT_DIR=$PWD/work/$1

# Create output directory if it does not already exist.
mkdir -p $OUT_DIR

# Clean previous simulation outputs.
rm -rf $OUT_DIR/*

# Move into output directory.
cd $OUT_DIR

# echo = Print output on terminal/screen : echo "message"
echo "run.sh | Running Test : $1 "

echo "run.sh | riscv64-unknown-elf-gcc -march=rv64gc -mabi=lp64 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -DENTROPY=0x9629af2 -std=gnu99 -O2 -I$TEST_HOME/env -T$TEST_HOME/env/link.ld $TEST_HOME/directed_tests/$2/$1.S -o $OUT_DIR/$1.elf"

# Compile RISC-V Assembly (.S) into ELF executable.

riscv64-unknown-elf-gcc -march=rv64gc -mabi=lp64 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -DENTROPY=0x9629af2 -std=gnu99 -O2 -I$TEST_HOME/env -T$TEST_HOME/env/link.ld $TEST_HOME/directed_tests/$2/$1.S -o $OUT_DIR/$1.elf

echo "run.sh | riscv64-unknown-elf-objdump --disassemble-all --disassemble-zeroes --section=.text --section=.text.startup --section=.text.init --section=.data $OUT_DIR/$1.elf > $OUT_DIR/$1.disass"

# Convert ELF into human-readable assembly (disass).

riscv64-unknown-elf-objdump --disassemble-all --disassemble-zeroes --section=.text --section=.text.startup --section=.text.init --section=.data $OUT_DIR/$1.elf > $OUT_DIR/$1.disass

echo "run.sh | timeout --foreground 60s spike  --log-commits --log  spike.dump --isa=rv64gc +signature=spike_signature.txt +signature-granularity=4 $OUT_DIR/$1.elf"

# Execute ELF on Spike ISS.
# Spike acts as the Reference Model.
# Generates: spike.dump
# timeout 60s: Prevents simulation hang.
timeout --foreground 60s spike  --log-commits --isa=rv64gc -l $OUT_DIR/$1.elf &> spike.dump

echo "run.sh | elf2hex  4  4194304 $1.elf 2147483648 > code.mem"

# elf2hex -> Utility used to convert ELF into HEX format.
# 4194304 -> Total memory size in bytes. -> 4194304 Bytes = 4 MB.
# $1.elf -> Input ELF executable generated by GCC.
# 2147483648 -> Base address where ELF is mapped. -> Decimal value of 0x80000000 starting addresss.
# > code.mem -> Redirect generated HEX output into code.mem.
elf2hex  4  4194304 $1.elf 2147483648 > code.mem

# Return back to original directory.
cd $TEST_HOME


